{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flink-healthcare-molina.fullname" . }}-ingress
  # annotations:
  #   kubernetes.io/ingress.class: azure/application-gateway
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - http:
        paths:
        {{- range .paths }}
        - path: {{ .path }}
          backend:
            service:
              name: {{ include "flink-healthcare-molina.fullname" $ }}-rest
              port:
                number: {{ $.Values.service.port }}
          {{- with .pathType }}
          pathType: {{ . }}
          {{- end }}
        {{- end }}
      {{- end }}
{{- end }}